install.packages('remotes')
remotes::install_github('epiforecasts/scoringutils')
remotes::install_github('reichlab/covidHubUtils')
remotes::install_github("Chicago/RSocrata")
install.packages(c('tidyverse', 'jsonlite', 'here'))
